Document: fichier
Title: Debian fichier Manual
Author: <insert document author here>
Abstract: This manual describes what fichier is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/fichier/fichier.sgml.gz

Format: postscript
Files: /usr/share/doc/fichier/fichier.ps.gz

Format: text
Files: /usr/share/doc/fichier/fichier.text.gz

Format: HTML
Index: /usr/share/doc/fichier/html/index.html
Files: /usr/share/doc/fichier/html/*.html
